### ISSUE TITLE
class with Api annotation without Route annotation inside crash the build process

### ISSUE THREAD

**Issue by Kleak** [Jaguar-dart/jaguar#15]
Something like that is not accepted and should be

```dart
@Api(path: 'api')
class MedisApi extends Object with _$JaguarMedisApi {
  @Group(path: 'users')
  UsersResource users = new UsersResource();
}
```

**Comment by Kleak** [comment]
here is the exact error:
```
[SEVERE] medis|lib/server/api/api.dart: Error running ApiGenerator for class MedisApi.
Bad state: No element
#0      ListIterable.firstWhere (dart:_internal/iterable.dart:107)
#1      parseRoute (package:jaguar/generator/parser/route/import.dart:24:6)
#2      collectRoutes.<anonymous closure> (package:jaguar/generator/parser/route/import.dart:34:27)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:416)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:344)
#5      WhereIterator.moveNext (dart:_internal/iterable.dart:442)
#6      List.List.from (dart:core-patch/array_patch.dart:46)
#7      Iterable.toList (dart:core/iterable.dart:349)
#8      collectRoutes (package:jaguar/generator/parser/route/import.dart:56:8)
#9      collectAllRoutes (package:jaguar/generator/parser/group/import.dart:36:7)
#10     collectAllRoutes.<anonymous closure> (package:jaguar/generator/parser/group/import.dart:46:16)
#11     MappedListIterable.elementAt (dart:_internal/iterable.dart:416)
#12     ListIterator.moveNext (dart:_internal/iterable.dart:344)
#13     WhereIterator.moveNext (dart:_internal/iterable.dart:442)
#14     Iterable.forEach (dart:core/iterable.dart:227)
#15     collectAllRoutes (package:jaguar/generator/parser/group/import.dart:50:8)
#16     ApiGenerator.generateForAnnotatedElement.<generateForAnnotatedElement_async_body> (package:jaguar/generator/hook/api/import.dart:44:9)
#17     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#18     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
#19     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:48)
#20     _rootRun (dart:async/zone.dart:1146)
#21     _CustomZone.run (dart:async/zone.dart:1026)
#22     _CustomZone.runGuarded (dart:async/zone.dart:924)
#23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#24     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
#25     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:48)
#26     _rootRun (dart:async/zone.dart:1150)
#27     _CustomZone.run (dart:async/zone.dart:1026)
#28     _CustomZone.runGuarded (dart:async/zone.dart:924)
#29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)```

**Comment by tejainece** [comment]
https://github.com/Jaguar-dart/jaguar/pull/16

@Kleak The above pull request might fix the issue. I haven't tested it. Can you test it and let me know? Thanks.

**Comment by Kleak** [comment]
fixed
